dm_me/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from index.views import *
from blog.views import *
from verify.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",landing_view,name="landingView"),
    path("privacy-policy/",privacy_policy_view,name="privacyPolicyView"),
    path("blog/<slug:slug>",blog_view,name="blogView"),
    path("blog/",blogs_view,name="blogsView"),
    path("home/",index_view,name="indexView"),
    path("guest/",guest_view,name="guestView"),
    path("login/",login_view,name="loginView"),
    path("logout/",logout_view,name="logoutView"),
    path("signup/",signup_view,name="signupView"),
    path('pwd_reset/',pwd_reset_view, name='pwdReset'),
    path("inbox/",inbox_view,name="inboxView"),
    path("inbox/<int:pk>",dm_view,name="dmView"), 
    path("queries/",queries_view,name="queriesView"),
    path("block/<int:pk>", block_view,name="blockView"),
    path("edit-reply/<int:pk>",edit_reply_view,name="editReplyView"),
    path("user/",user_profile_view,name="userProfileView"),
    path("edit-profile/",edit_profile_view,name="editProfileView"),
    path("settings/",settings_view,name="settingsView"),
    path("user/<str:username>/",profile_view,name="profileView"),

]+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

index/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from datetime import timedelta
# Create your models here.

class emojis(models.Model):
  name = models.TextField(blank=False,null=False)
  data = models.TextField(blank=False,null=False)

  def __str__(self):
    return self.name

class IP(models.Model):
  address = models.GenericIPAddressField(unique=True)
  owner = models.ForeignKey(User, null=True,default= None, on_delete=models.SET_DEFAULT )
  banned = models.BooleanField(default=False)
  createdAt = models.DateTimeField(auto_now_add=True, null=True)

  def __str__(self):
    return self.address

#tier 1 = guests
#tier 2 = normal users
#tier 3 = pro users

class profile(models.Model):
  user = models.OneToOneField(User,on_delete=models.CASCADE)
  bio = models.TextField(default="Send anonymous messages to me !")
  dp = models.ImageField(default="", blank= True, upload_to="veil/static/profile_pics/")
  bg_color = models.CharField(default="", blank=True, null=True, max_length=7)
  dms_count = models.IntegerField(default=0)
  blocked_ips = models.ManyToManyField(IP,blank=True)
  is_open = models.BooleanField(default=True)
  tier = models.IntegerField(default=1, blank=False,null=False)
  secque = models.CharField(max_length=255, blank=True, default='')

  def __str__(this):
    return this.user.username +" - "+ this.user.first_name + " [ "+str(this.dms_count)+" ]"

@receiver(pre_delete, sender=profile)
def delete_profile_picture(sender, instance, **kwargs):
    instance.dp.delete()

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
  if created :
    profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
  instance.profile.save()


class dm(models.Model):
  message = models.TextField(null=True)
  sentTo = models.ForeignKey(User, on_delete=models.CASCADE)
  sentAt = models.DateTimeField(auto_now_add=True)
  opened = models.BooleanField(default=False)
  sentBy = models.ForeignKey(IP, null=True, on_delete=models.SET_NULL)
  isNotif = models.BooleanField(default=False)
  isQuery = models.BooleanField(default=False)
  viewOnce = models.BooleanField(default=False, null = False, blank=False)
  dmType = models.IntegerField(null=False, blank=False, default=1)
  img = models.TextField(null=True,blank=True)

  def __str__(self):
    return self.sentTo.first_name+" [ "+(self.sentAt+ timedelta(hours=5,minutes=30)).strftime("%d/%m/%Y  %H:%M") +" ] :"+str(self.dmType)

@receiver(pre_delete,sender=dm)
def delete_ip(sender,instance,**kwargs):
    ip = instance.sentBy
    if ip.banned == False :
        if not profile.objects.filter(blocked_ips = ip).exists():
            if len( dm.objects.filter(sentBy = ip) ) <= 1 :
                ip.delete()


class reply(models.Model):
    reply = models.TextField()
    replyTo = models.ForeignKey(dm, on_delete = models.CASCADE)
    replyAt = models.DateTimeField(auto_now_add=True)
    pinned = models.BooleanField(default=False)

    def __str__(self):
        return self.replyTo.sentTo.username+" [ "+(self.replyAt+ timedelta(hours=5,minutes=30)).strftime("%d/%m/%Y  %H:%M") +" ]"

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="google-site-verification" content="oevM4pLBZYtVbL3C19lM9d9XNbPJ2T0FEmSF88sBrv0" />
    <meta name="google-adsense-account" content="ca-pub-2048058446252128">
    <meta property="snapchat:app_id" content="ea45481c-92de-4693-ab17-3e324f5e87b9"/>
    <meta name="theme-color" content="#00ee6e">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link crossorigin='anonymous' href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,100;9..40,200;9..40,300;9..40,400;9..40,500;9..40,600;9..40,700;9..40,800;9..40,900&display=swap" rel="stylesheet">

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-F6SFLKM3E0"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-F6SFLKM3E0');
    </script>

    <link rel="icon" type="image/png" href="/static/veil-logo.svg">

    <meta property="og:site_name" content="veil msg">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@veil_msg">

    {% if title %}
        {% firstof title as title_act %}
    {% else %}
        {% firstof 'Secret Message Link | VeilMsg' as title_act %}
    {% endif %}

    <title>{{ title_act }}</title>
    <meta name="og:title" content="{{ title_act }}">
    <meta name="twitter:title" content="{{ title_act }}">

    <meta name="description" content="With veil, you can communicate anonymously with your friends. You don't need to reveal your identity to send messages. Have fun !!">
    <meta name="og:description" content="With veil, you can communicate anonymously with your friends. You don't need to reveal your identity to send messages. Have fun !!">
    <meta name="twitter:description" content="Let your friends share their questions anonymouslyy. Have fun !!">

    {% if not userdp %}
    <meta name="og:image" content="https://veilmsg.pythonanywhere.com/static/veil-ask-anon-5.jpg"/>
    <meta name="twitter:image" content="https://veilmsg.pythonanywhere.com/static/veil-ask-anon-5.jpg"/>
    {% else %}
    <meta name="og:image" content="https://veilmsg.pythonanywhere.com{{ userdp}}">
    <meta name="twitter:image" content="https://veilmsg.pythonanywhere.com{{userdp}}" >
    {%endif%}
    <meta property="snapchat:sticker" content="https://veilmsg.pythonanywhere.com/static/sticker.png"/>

    <script type="application/ld+json">
    {
         "@context": "https://schema.org/",
         "@type": "WebSite",
         "name": "VeilMsg",
         "alternateName" : ["Veil Msg","Veil Message"],
         "url": "https://veilmsg.pythonanywhere.com"
    }
    </script>

    {% block head_content %}
    {% endblock %}
      <style type="text/css" media="all">
      :root {
         --t1 : rgba(255,255,255,.85);
         --t2 : rgba(255,255,255,.65);
         --t3 : rgba(255,255,255,.35);
         --t4 : rgba(255,255,255,.10);

         --black : #202020;

         --red : #f62a44; 

         --base : #0066ff; 
         --base-light : #50c7fb;
         --base-grad : linear-gradient(to top right, var(--base), var(--base-light)); 
         --base-grad-orange : linear-gradient(45deg, #ff5c00, #ffba1f);

         --base-bg-dark : #efefef;
         --base-bg-mid : #f8f8f8;
         --base-bg-light : #ffffff;

         --base-text-mid : #606060;
         --base-text-light : #808080;
         --base-text-dark : #404040;

         --gray-light : #eee;
         --gray-mid : #cfcfcf;
         --gray-dark : #bbb;
       }
      * {
        box-sizing: border-box;
        margin : 0;
        padding: 0;
      }
      html {
        scroll-behavior: smooth;
        font-size: 16px;
      }
      img {
        width : 100%;
      }
      body {
        width : 100vw;
        font-family: "DM Sans",Sans-Serif;
        font-size: 16px;
        z-index: 0;
      }
      @media (min-width: 768px) {
        body {
            font-size: 18px;
        }
      }
      .ad {
          width : 100%;
          overflow-x : auto;
          background : #eee;
          border-radius : .25em;
          padding : .25em;

         display : grid;
         grid-template-columns : 1fr ;
         place-items : center;
      }
      .ad *{
          border-radius : .25em;
      }
      .stiff {
        max-width: 500px;
        margin : 0 auto !important;
      }
      .landing-stiff {
        max-width: 1000px;
        margin : 0 auto !important;
      }
      .alert-bowl {
        width : 100%;
        height : 100%;
        background : rgba(0,0,0,.75);
        padding : 1em 1.5em;
        overflow-y : scroll;

        position: fixed;
        top : 0;
        left : 0;
        z-index: 155;

        display: none;
        grid-template-columns: 1fr;
        place-items: center;
      }
      .alert-cont {
        background : var(--base-bg-light);
        border-radius: 1em;
        padding : .75em ;

        display: grid;
        grid-template-columns: 1fr;
        place-items: center;
        grid-gap: .75em;
      }
      .alert-box {
        min-width: 200px;
        padding : 1em;
        background : var(--base-bg-mid);
        color : var(--base-text-mid);
        font-size: 1rem;
        font-weight: 600;
        border-radius: .65em;
        text-align: center;
      }
      .alert-box p {
        width : 100%;
      }
      .alert-cont #alert-btn {
        padding : .35em 1em;
        font-family : inherit;
        font-weight: 1000;
        color : var(--base-text-dark);
        font-size: 1.25rem;
        background : none;
        outline: none;
        border : none;
      }
      .veil-input {
        width : 100%;
        background : var(--base-bg-dark);
        font-family: inherit;
        font-size: 1em;
        color : var(--base-text-dark);
        padding : .75em 1em;
        border-radius: .5em;
        border: none;
        outline: none;
      }
      .veil-input::placeholder {
        color : var(--base-text-light);
      }
      .veil-button {
        width : 100%;
        padding : .7em 1em;
        border-radius: 100em;
        border :none;
        background : var(--base-grad);
        color : var(--base-bg-light); 
        text-transform: uppercase;

        font-weight: 1000;
        font-size: 1rem;
        font-family: inherit;
        transition : .25s;
      }
      .veil-button:hover {
        animation: .2s btnClick;
      }
      .register-cont {
        width : 100%;
        padding : .5em ;

        display: grid;
        grid-template-columns: 1fr;
        place-items: center end;
        grid-gap : .5em;
      }
      .register-cont a {
        color : var(--base-text-dark);
        transition : .5s;
        font-size: .85em;
      }
      .register-cont p {
        color : var(--base-red);
        font-size: .85em;
      }
      .register-cont a:hover {
        text-decoration: none;
      }

      @keyframes btnClick {
        0% {
          transform : scale(1);
        }
        50% {
          transform : scale(.9);
        }
        100% {
          transform : scale(1);
        }
      }
      .gap {
        height : 3em;
      }
      #wrap {
        width : 100%;
        z-index: 2;
      }
      .hide {
        display : none !important;
      }
      .highlight {
          color : var(--base-blue) !important;
      }
      .veil-dp {
          background : var(--black);
          border-radius: 50%;
          width : 4.65rem;
          height : 4.65rem;
          padding : .5em;

          display: grid;
          grid-template-columns: 1fr;
          place-items: center;
    }
    .veil-dp img {
        width : 100%;
        aspect-ratio : 1/1;
        object-fit: cover;
        border-radius : inherit;
    }
    input[type="radio"], input[type='checkbox'] {
      position: relative;
      width: 15px;
      height: 15px;
      border-radius: 50%;
      appearance : none;
    }

    input[type="radio"]::before ,  input[type='checkbox']::before{
      content: "";
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      width: 15px;
      height: 15px;
      border-radius: 50%;
      background-color: #fff;
      border : .1em solid var(--gray-dark);
    }
    input[type="radio"]:checked::before,  input[type='checkbox']:checked::before {
      background: radial-gradient(circle closest-side at center, var(--base-text-mid) 0%, var(--base-text-mid) 75%, #fff 75%);
    }

    </style>

  </head>
  <body>


    <div class="alert-bowl">
      <div class="alert-cont">
        <div class="alert-box">
          <p id="alert-msg">this is a random message</p>
        </div>
        <button onclick="closeAlert()" id="alert-btn">okay</button>
        <button class="veil-button hide" id="alert-btn-guest">join us</button>
      </div>
    </div>
    <script>
      var alertBowl = document.querySelector(".alert-bowl")
      var alertMsg = document.querySelector("#alert-msg")
      var alertBtn = document.querySelector("#alert-btn")
      var alertBtn2 = document.querySelector("#alert-btn-guest");

      function alertDm(text){
        alertBowl.style.display = "grid";
        alertMsg.innerHTML = text;
      }
      function alertDm2(text,cta,cta_link){
        alertBowl.style.display = "grid";
        alertMsg.innerHTML = text;
        alertBtn.style.display = "none";
        alertBtn2.classList.remove("hide")

        alertBtn2.innerHTML = cta;
        alertBtn2.onclick = function(){
            window.location = cta_link;
        }
      }
      function closeAlert(){
        alertBowl.style.display = "none";
      }
      function closeAlertImg(){
          document.querySelector('.img-alert-bowl').style.display = "none";
      }
      function confirmDm(text,e){
        var x = confirm(text)
        if ( x == true ){
          window.location = e.target.closest("a").href
        }
        e.preventDefault();
      }

      async function shareImage(kurl,fname) {

        if (! navigator.canShare ) {
          alertDm("Your browser doesn't support sharing !");
          return
        }
        try {
          const response = await fetch(kurl);
          const blob = await response.blob();
          const filesArray = [
            new File(
              [blob],
              fname,
              {
                type: blob.type,
                lastModified: new Date().getTime()
              }
           )
          ];
          const shareData = {
            files: filesArray,
          };

          await navigator.share(shareData);

        }catch (error){
          alertDm(`error : ${error.message}`);
        }
      }
    </script>

    <div id="wrap">
      {% block base_content %}
      {% endblock %}
    </div>

    {% include 'footer.html' %}

    {% if status %}
        <script>alertDm("{{ status }}");</script>
        {% if not request.user.is_authenticated %}
            <script>
                setTimeout(function() {
                    alertDm2("Let your friends ask you anonymous questions too !", "Join now", '/')
                }, 1000);
            </script>
        {% endif %}
    {% endif %}

    <script>
    </script>
  </body>
</html>

templates/base_header.html
<style>
  header {
    width : 100%;
    padding : .75em 1.25em;
    background: var(--base-bg-light);
    border-bottom: .1em solid var(--base-bg-dark);

    position: fixed;
    top : 0;
    left : 50%;
    transform: translateX(-50%);
    z-index: 100;

    display: flex;
    justify-content : space-between;
    align-items: center;
    gap : 2em;
  }
  .logo {
    /* margin: .25em 0 0 0 ; */
    width : 3em;
  }
  .signup-link {
    text-decoration : none;
    color : var(--base);
    font-weight: 1000; 
    text-transform : uppercase;
    transition : .25s;
  }
  .signup-link:hover {
    color : var(--base-text-dark);
  }

</style>
<header class="stiff">
  <a href="/" class="logo"><img src="/static/veil-logo-2.svg" alt="veil logo"></a>
  <a href="/" class="signup-link"> Create your veil link</a>
</header>
<div class="gap"></div>

templates/edit_profile.html
{% extends "base_index.html" %}
{% block content %}
  {% include "second_header.html" %}

  <style>
    .edit-bowl {
      width : 100%;
      padding : 2em;

      display: grid;
      grid-template-columns: 1fr;
      place-items: start;
      grid-gap: .75em;
    }
    .edit-cont {
      width : 100%;
      padding : 1em 0 ;

      display: grid;
      grid-template-columns: 1fr;
      place-items: start;
      grid-gap: 1.25em;
    }
    .edit-box {
      width : 100%;
    }
    .edit-box p {
      font-size: .9rem;
      margin-bottom: .2rem;
      color : var(--base-text-light);
    }

    #profile_bg {
      height : 3em;
      width : 5em;
    }
    input[type="color"]::-webkit-color-swatch-wrapper {
      padding: 0;
      border-radius : .35em;
    }
    input[type="color"]::-webkit-color-swatch {
      border: none;
      border-radius : .35em;
    }
    .register-cont {
      width : 100%;
      padding : 0 .5em ;

      display: grid;
      grid-template-columns: 1fr;
      place-items: center end;
    }
    .register-cont p {
      color : var(--base-red);
      font-size: .85em;
    }
    .quick-dp-bowl {
        width : 100%;
        padding : 1em 0 0 0;

        display : flex;
        justify-content : flex-left;
        align-items : center;
        gap : .2em;
    }
    .quick-dp {
        background : var(--base-bg-dark);
        padding : .15em .3em;
        font-size : 1.25em;
        border-radius : 50%;
    }
  </style>
  <div class="edit-bowl stiff">
    <form class="edit-cont" action="" method="POST"> {% csrf_token %}
      <div class='veil-dp'>
        {% if user.profile.dp == "" %}
           <img class="veil-picture-preview" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIOwIePvlZCteninGWvsSIJ64QcrEtxMce8A&usqp=CAU">
        {% else %}
           <img class="veil-picture-preview" src="{{ userdp }}">
        {% endif %}
      </div>
      <div class="edit-box">
        <p>veil-picture</p>
        <input type="file" class="veil-input veil-picture-input">
        <input type="hidden" class="veil-picture-send" name="veil" id="veil"/>
        <div class='quick-dp-bowl'>
            {% for emoji in emojis %}
                <div class='quick-dp' onclick='document.querySelector(".veil-picture-send").value = "{{ emoji.data }}"; document.querySelector(".veil-picture-preview").src = "{{ emoji.data }}";'>{{ emoji.name }}</div>
            {% endfor %}
        </div>
      </div>
      <div class="edit-box">
        <p>name</p>
        <input type="text" class="veil-input" name="name" id="name" value="{{ user.first_name }}" max_length='25' minlength='2' required/>
      </div>
      <div class="edit-box">
        <p>profile background</p>
        <input type="color" class="veil-input" name="profile_bg" id="profile_bg" value="{{ user.profile.bg_color }}" max_length='7' minlength='0' required/>
      </div>
      <div class="edit-box">
        <p>bio</p>
        <textarea name="bio" class="veil-input" id="bio" rows="2" cols="40" placeholder="Type your bio here... " required>{{ user.profile.bio }}</textarea>
      </div>

      <div class="register-cont">
        <p class="error">{{ error }}</p>
      </div>
      <button type="submit" class="save-edit-btn veil-button">Save</button>
    </form>
  </div>
  <script>
    secondHeader("edit profile","/user/");

    // let usrname = document.querySelector('#username')
    // usrname.addEventListener('input',function(e){
    //     usrname.value = usrname.value.replaceAll(" ", "_");
    //     usrname.value = usrname.value.toLowerCase()
    // })

    document.querySelector(".veil-picture-input").addEventListener("change", function(event) {
      var img = new Image();
      img.onload = function() {
        var canvas = document.createElement("canvas");
        var ctx = canvas.getContext("2d");

        // Set desired width and height for resized image
        var newWidth = 200;
        var newHeight = 200;

        // Calculate aspect ratio of original image
        var aspectRatio = img.width / img.height;

        // Calculate new width and height while maintaining aspect ratio
        if (img.width > img.height) {
        newHeight = Math.round(newWidth / aspectRatio);
        } else {
        newWidth = Math.round(newHeight * aspectRatio);
        }

        // Set canvas size to new width and height
        canvas.width = newWidth;
        canvas.height = newHeight;

        // Draw the image onto the canvas
        ctx.drawImage(img, 0, 0, newWidth, newHeight);

        // Get the resized image data as a base64-encoded string
        var resizedImageData = canvas.toDataURL("image/png", 0.8); // 0.8 is the quality

        // Handle the resized image data as needed, e.g. upload to server, display preview, etc.
        // Here you can use methods such as FileReader or FormData to handle the image data.
        document.querySelector(".veil-picture-send").value = resizedImageData;
        document.querySelector(".veil-picture-preview").src = resizedImageData;
      };
      img.src = URL.createObjectURL(event.target.files[0]);
    });
  </script>
{% endblock %}

templates/footer.html
<style>
    .footer-bowl {
        width: 100%;
        margin-top : 5em;
        background: #000000;
        padding : 5em 2em 5em 2em;
        border-top: 0.5em solid rgba(255,255,255,.65);
      }
      .footer-msg {
         width : 100%;
         color : var(--base-text-light);
         padding : .5em;
         text-align : center;
      }
      .footer-cont {
        width :100%;

        display: grid;
        grid-template-columns: 1fr;
        place-items: center;
        grid-gap: 2em;
      }
      .footer-cont img {
        width: 5em;
      }
      .footer-cont div {
        width: 100%;

        display: flex;
        justify-content: center;
        place-items: center;
        gap: 1em;
      }
      .footer-cont a {
        font-size: 1em;
        text-decoration: none;
        text-align: center;
        color: var(--base-bg-dark);
      }
      .footer-bottom a {
        background: var(--base-text-dark);
        border-radius: 10em;
        padding: .75em 1em;
        transition: .2s;
      }
      .footer-bottom a:hover {
        background: var(--base-text-mid);
      }
      .donatebtn {
          background : var(--gray-light);
          color : var(--base-tedxt-dark) !important;
          padding: .75em 1em;
          border-radius: 102em;
          font-weight : bold;
      }
    .donatebtn:hover {
        animation : .2s btnClick;
    }
</style>
<div class="footer-bowl">
    <div class="footer-msg">80,000+ Secrets Sent, 0 Faces Revealed 🤫</div>
    <div class="footer-cont landing-stiff">
        <img src="/static/veil-logo.svg" alt="veil logo">
        <div class="footer-top">
            <a href="/privacy-policy">Privacy Policy</a>
            <a href="/blog/">Blog</a>
            <a href="/user/admin/">Contact Us</a>
            <a href="https://bento.me/veilmsg">Other Links</a>
        </div>
        <div class="footer-bottom">
            <a href="https://instagram.com/veil.msg" target="_blank"><i class="bi-instagram"></i></a>
            <a href="https://twitter.com/veil_msg" target="_blank"><i class="bi-twitter"></i></a>
            <a rel="me" href="https://mastodon.social/@veilmsg"><i class="bi-mastodon"></i></a>
        </div>
        <a class='donatebtn' href='https://buymeacoffee.com/veilmsg' target='_blank'>🔥 Fuel Us: Donate Now !</a>
    </div>
</div>

templates/settings.html
{% extends "base_index.html" %}
{% block content %}
  {% include "second_header.html" %}

  <style>
    .settings-bowl {
      width : 100%;
      padding : 1em;

      display: grid;
      grid-template-columns: 1fr;
      place-items: center;
      grid-gap: 1.25em;
    }
    .settings-cont {
      width : 100%;
      background : var(--base-bg-dark);
      padding : 1.25em;
      border-radius: 1em;

      display: grid;
      grid-template-columns: 1fr;
      place-items: start;
      grid-gap: 1em;
    }
    .settings-cont h3 {
      width : 100%;
      text-transform: lowercase;
      font-weight: 1000;
      color : var(--base-text-mid);
    }
    .settings-box {
      width : 100%;
      padding : 0 .5em;
      text-decoration: none;
      color : var(--base-text-mid);
      /*background: var(--base-bg-dark); */

      display : flex;
      justify-content: space-between;
      align-items: center;
      gap : .5em;
    } 
    .settings-box div {
      width : 100%;
      display : flex;
      justify-content : space-between;
      align-items :center;
    }
    #id_is_open {
        width : 1.25em;
        height: 1.25em;
    }
  </style>
  <div class="settings-bowl stiff">
    <div class="settings-cont">
      <h3>blocked</h3>
      {% for blocked_ip in user.profile.blocked_ips.all %}
        <a href="{% url 'blockView' blocked_ip.pk %}?unblock=true" onclick="confirmDm('Do you really want to unblock user {{ blocked_ip.id }}',event)" class="settings-box">
          <p>blocked user {{ blocked_ip.id }}</p>
          <i class="bi-three-dots"></i>
        </a>
      {% endfor %}
    </div>
    <div class="settings-cont">
      <h3>account</h3>
      <form action = "" method = "post" class="settings-box open-status-form">
        {% csrf_token %}
        {{ form }}
      </form>

      <a href="/logout/" onclick="confirmDm('Do you really want to logout ?',event)" class="settings-box">
        <p>logout</p>
        <b>⛔️</b>
      </a>
    </div>
    <div class="settings-cont">
      <h3>veil</h3>
      <a href="/user/admin/" class="settings-box">
        <p>contact</p>
        <b>💬</b>
      </a>
      <a href="#" class="settings-box">
        <p>version</p>
        <b>2.1</b>
      </a>
    </div>
  </div>
  <script>
    secondHeader("settings","/user/")

    var opform = document.querySelector('.open-status-form')
    var opinput = document.querySelector('#id_is_open')

    opinput.addEventListener('click',function(event){
        var agreed = true
        if (! opinput.checked){
            var agreed = confirm('By clicking OK you will not receive any dms')
        }
        if (agreed){
            opform.submit()
        }
        event.preventDefault()
    })

  </script>
{% endblock %}